# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blog-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: blog-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false   # tắt auth cho dễ test
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  api:
    build: ./api
    container_name: blog-api
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: blog_user
      DB_PASS: blog_pass
      DB_NAME: blog_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_HOST: http://elasticsearch:9200

volumes:
  postgres_data:
  es_data:
