version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: golang
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: blog-redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: blog-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  api:
    build:
      context: .
    container_name: blog-api
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://new_user:abcd1234@postgres:5432/golang?sslmode=disable
      REDIS_ADDR: redis:6379
      ES_URL: http://elasticsearch:9200

volumes:
  postgres_data:
  es_data:
